# Copyright 2018 Pulse Secure, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# The following two ConfigMaps can be updated or overridden to supply
# configuration to the traffic manager at deploy time or when the
# traffic manager is running. See vtm-example-config.yaml and
# vtm-example-data.yaml for examples.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vtm-config
  labels:
    app: vtm
data:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vtm-extra-data
  labels:
    app: vtm
data:

---
# The rest of the manifest deploys a traffic manager with basic
# configuration and tools for running in a Kubernetes cluster.

# The administrative password is automatically generated by the
# traffic manager and can be viewed in its log output. To specify a
# password, set the ZEUS_PASS environment variable in the Deployment
# manifest.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vtm-base-config
  labels:
    app: vtm
data:
  config: |
    version: 6.2

    global_settings:
      properties:
        java:
          enabled: false

        fault_tolerance:
          frontend_check_ips: []

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vtm-healthcheck-config
  labels:
    app: vtm
data:
  config: |
    version: 6.2
    virtual_servers:
    - name: healthcheck
      properties:
        basic:
          enabled: true
          port: 19999
          protocol: http
          pool: discard
          request_rules: [ "internal_healthcheck" ]

    rules:
    - name: internal_healthcheck
      content: http.sendResponse( '200 OK', 'text/plain', '', '');

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtm
  labels:
    app: vtm
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: vtm
  template:
    metadata:
      labels:
        app: vtm
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: vtm
          image: pulsesecure/vtm:latest
          imagePullPolicy: Always
          ports:
          - name: vtm-webui
            containerPort: 9090
            protocol: TCP
          - name: vtm-restapi
            containerPort: 9070
            protocol: TCP

          securityContext:
            capabilities:
              add:
                - SYS_RESOURCE
                - NET_ADMIN

          livenessProbe:
            httpGet:
              path: /
              port: 19999
              scheme: HTTP
            failureThreshold: 10
            successThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 5
            initialDelaySeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 19999
              scheme: HTTP
            failureThreshold: 2
            successThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 1

          env:
          - name: ZEUS_EULA
            value: accept
          - name: ZEUS_COMMUNITY_EDITION
            value: "yes"
          - name: ZEUS_WATCHED_CONFIG
            value: "/import"
          - name: ZEUS_CONFIG_IMPORT_ARGS
            value: --no-replicate

          volumeMounts:
          - name: config-volume
            mountPath: /import/config
          - name: data-volume
            mountPath: /import/data

          terminationMessagePolicy: FallbackToLogsOnError

      volumes:
      - name: config-volume
        projected:
          sources:
          - configMap:
              name: vtm-base-config
              items:
              - key: "config"
                path: 00-vtm-base-config.yaml
          - configMap:
              name: vtm-healthcheck-config
              items:
              - key: "config"
                path: 00-vtm-healthcheck-config.yaml
          - configMap:
              name: vtm-config

      - name: data-volume
        projected:
          sources:
          - configMap:
              name: vtm-extra-data

---
